--- #YAML:1.0
name:               Mojolicious-Plugin-DigestAuth
version:            0.08
abstract:           HTTP Digest Authentication for Mojolicious
author:
    - Skye Shaw <sshaw AT lucas.cis.temple.edu>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mojolicious:  2.20
resources:
    bugtracker:  http://github.com/sshaw/Mojolicious-Plugin-DigestAuth/issues
    repository:  http://github.com/sshaw/Mojolicious-Plugin-DigestAuth
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
